on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig fmt --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.6'
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: sudo apt install autoconf libtool pkg-config make libzstd-dev libfuse3-dev
      - run: zig build -Doptimize=ReleaseSafe -Dtarget=x86_64-linux-musl
      - run: zig-out/bin/dockerc --image docker://hello-world --output enlo
      - run: ./enlo